language: python
python:
- 3.5
install:
- pip install six pyyaml requests markdown2 jinja2
script:
- python validate_entries.py
deploy:
  provider: script
  script: site_generator/travis_deploy
  on:
    repo: aasorg/hacks-collector
    branch: master
env:
  global:
    secure: Yvt1HnVCz4EEg6X7+zmXdjqLSqOU67YSeNJHvPnPNRQMR0qYaFSiprCflm6QoRj7HjVr6FJEJQ19fOFNvue35pnwvVbcBHG5NKR9qJ2ykgVK2rS87yFeY/0Fj3wPtUlO7rp6QkgM8q+UDDYR4d8VgaYWhc6i2lEDeNttnq4k0vM8iCPeLcT0bIjyVwAiqTkr4BwerIqhkLHfNCwZHh0jnpzhXvZDJ5UZ+r5RFHeHRHtQ67aTeQlXABvor+fG+woUfiKv8mmpU4YQQlquAvSdf952/fRb+Wuz6QpI5uEBTkKHeQMbTlCrLswoIbXFygb1NnO/exabm3LaxyQoubuQTzOmUKRWxck8FjwQG4hIHamo63ngAZpbsNv2+sw8Asbp0nmT26blmrUvJe2SpEkR4loUFCYDygM0rtwf0dNU9nwKfd9DenhQaNoHCFnofMCIV+hY4r0N7Rf40BaaBcoQHqvQXF+JJCRsaV/DG9mBSv9tlkOKIoMdWCMseCaEwL3fYGxFMpWSzQxX1rEQeQS70lqTrWmFkI5hHoFMR/T+8NOuAKC/BQIAe8uQthA7uDzZeZi+bJQaTBktwDhxX/9IW3Kl5nGFQprreWCysnPAbfi4+DNLYOLSTB/ACvMCjbWB7PwfIfnED1ZlKP9deoJcuoG7HghK20/upTbt1LVFLwI=
